# Vamos a visualizar el psv resultante del script

### Librerias necesarias

In [60]:
import pandas as pd

### Lectura de archivo psv en el formato correspondiente

In [58]:
df = pd.read_csv('starts_data.psv', delimiter='|', encoding='utf-8', low_memory=False)

### Lectura del archivo PSV como si fuera un CSV

In [62]:
# Especificamos el delimitador '|' porque los valores están separados por este carácter
df = pd.read_csv('starts_data.psv', delimiter='|', encoding='utf-8', low_memory=False)

### Resultado

In [63]:
df.head(10)

,id,hip,hd,hr,gl,bf,proper,ra,dec,dist,...,bayer,flam,con,comp,comp_primary,base,lum,var,var_min,var_maxa
0,0,NaN,NaN,NaN,NaN,NaN,Sol,0.000000,0.000000,0.0000,...,NaN,NaN,NaN,1.0,0.0,NaN,1.000000,NaN,NaN,NaN
1,1,1.0,224700.0,NaN,NaN,NaN,NaN,0.000060,1.089009,219.7802,...,NaN,NaN,Psc,1.0,1.0,NaN,9.638290,NaN,NaN,NaN
2,2,2.0,224690.0,NaN,NaN,NaN,NaN,0.000283,-19.498840,47.9616,...,NaN,NaN,Cet,1.0,2.0,NaN,0.392283,NaN,NaN,NaN
3,3,3.0,224699.0,NaN,NaN,NaN,NaN,0.000335,38.859279,442.4779,...,NaN,NaN,And,1.0,3.0,NaN,386.901132,NaN,NaN,NaN
4,4,4.0,224707.0,NaN,NaN,NaN,NaN,0.000569,-51.893546,134.2282,...,NaN,NaN,Phe,1.0,4.0,NaN,9.366989,NaN,NaN,NaN
5,5,5.0,224705.0,NaN,NaN,NaN,NaN,0.000665,-40.591202,257.7320,...,NaN,NaN,Phe,1.0,5.0,NaN,21.998851,NaN,NaN,NaN
6,6,6.0,NaN,NaN,NaN,NaN,NaN,0.001246,3.946458,55.0358,...,NaN,NaN,NaN,1.0,6.0,NaN,0.031420,NaN,12.462,12.162
7,7,7.0,NaN,NaN,NaN,NaN,NaN,0.001470,20.036114,57.8704,...,NaN,NaN,Peg,1.0,7.0,NaN,0.406256,NaN,NaN,NaN
8,8,8.0,224709.0,NaN,NaN,NaN,NaN,0.001823,25.886461,200.8032,...,NaN,NaN,Peg,1.0,8.0,NaN,8.425584,Z,11.748,7.648
9,9,9.0,224708.0,NaN,NaN,NaN,NaN,0.002355,36.585958,420.1681,...,NaN,NaN,And,1.0,9.0,NaN,56.337815,NaN,NaN,NaN